### ISSUE TITLE
CloudSight Query Delegates not called

### ISSUE THREAD

**Issue by smughal55** [cloudsight/cloudsight-objc#2]
The request seems to go through as I can see my usage stats increasing but I never get a response

**Comment by bfolkens** [comment]
There's all sorts of things to make sure you're doing correctly (with respect to Objective-C programming) to make sure the delegate is properly called...  I would first try requesting a token and retrieving the response manually first to make sure that is working, then move on to the delegate.

**Comment by sadanro100** [comment]
[[self delegate] cloudSightRequest:self didReceiveToken:self.token withRemoteURL:self.remoteUrl];
in CloudSightImageRequest.m does not trigger the event in CloudSightQuery.m

Any help?

**Comment by bfolkens** [comment]
Yes, as mentioned above, there are many things to check in your Objective-C code to ensure the delegate is called, the most important of which is assigning to a strong (retain) property on the parent controller so as not to lose the retaining scope if you allocate it to a variable in a method.
