### ISSUE TITLE
Delegate crashes on didFailWithError

### ISSUE THREAD

**Issue by obrhoff** [cloudsight/cloudsight-objc#4]
Please check if the delegate is implementing this method and conforms to protocol, because this is crashing if not implemented.

CloudSightQuery.m / Line: 66

```
- (void)cloudSightRequest:(CloudSightImageRequest *)sender didFailWithError:(NSError *)error
{
    [self.queryDelegate cloudSightQueryDidFail:self withError:error];
}
```

**Comment by bfolkens** [comment]
None of the protocol methods are marked optional.

**Comment by bfolkens** [comment]
Sorry, just noticed this is indeed a bug - seems this repo wasn't up to date with published Pod...
