### ISSUE TITLE
Implicit UIImage category dependency not set

### ISSUE THREAD

**Issue by caprahul** [cloudsight/cloudsight-objc#5]
The current cocoapods specs for this library don't pull down UIImage category. When doing a fresh installation the method signature aren't found 
`resizedImageWithContentMode: bounds: interpolationQuality:`

It will be helpful to have following cocopod dependency (or something else as appropriate)
[UIImage-Categories](https://github.com/mbcharbonneau/UIImage-Categories)

**Comment by bfolkens** [comment]
The example in the README.md file assumes some arbitrary image resizing code.  Updated now to avoid the complexity in the example (c6c72d863075c4d99acdc910d4f962757c6101fa), but you can use any image resizing code you'd like (there are tons on CocaPods).
