### ISSUE TITLE
Delegate methods are not getting called

### ISSUE THREAD

**Issue by Madyarora** [cloudsight/cloudsight-objc#6]
Hi,

After sending the request delegate methods are not getting called. Below is the line of code that I'm generating for the query.

CloudSightQuery *query = [[CloudSightQuery alloc] initWithImage:imageData
                                                         atLocation:CGPointMake(self.imageView.frame.origin.x, self.imageView.frame.origin.y)                                                      withDelegate:self
                                                        atPlacemark:location
                                                       withDeviceId:deviceIdentifier];
[query start];

**Comment by bfolkens** [comment]
One common problem with delegates is that, if they're not set to retain/strong in a property, then they'll be NULL by the time they're called.  Make sure your delegate is still retained in memory.  Let me know if that helps.
